// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "ASSETOBJ_PREFAB";
        public const string ASSETOBJ = "ASSETOBJ";
    }
    public class Scene_g_prefab
    {
        public const string BundleName = "SCENE_G_PREFAB";
        public const string SCENE_G = "SCENE_G";
    }
    public class Ui_knowledge_prefab
    {
        public const string BundleName = "UI_KNOWLEDGE_PREFAB";
        public const string UI_KNOWLEDGE = "UI_KNOWLEDGE";
    }
    public class Ui_main_prefab
    {
        public const string BundleName = "UI_MAIN_PREFAB";
        public const string UI_MAIN = "UI_MAIN";
    }
    public class Ui_start_prefab
    {
        public const string BundleName = "UI_START_PREFAB";
        public const string UI_START = "UI_START";
    }
    public class Uiconnect_prefab
    {
        public const string BundleName = "UICONNECT_PREFAB";
        public const string UICONNECT = "UICONNECT";
    }
    public class Uimsg_prefab
    {
        public const string BundleName = "UIMSG_PREFAB";
        public const string UIMSG = "UIMSG";
    }
    public class Uitestunirx_prefab
    {
        public const string BundleName = "UITESTUNIRX_PREFAB";
        public const string UITESTUNIRX = "UITESTUNIRX";
    }
}
